steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/switchboard-webapp', '-f', 'Dockerfile.webapp', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/switchboard-webapp']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/switchboard-websocket', '-f', 'Dockerfile.websocket', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/switchboard-websocket']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'switchboard',
      '--image', 'gcr.io/$PROJECT_ID/switchboard-webapp',
      '--image', 'gcr.io/$PROJECT_ID/switchboard-websocket',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--region', 'europe-west4',
    ]

options:
  logging: CLOUD_LOGGING_ONLY
