steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/switchboard', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/switchboard']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'switchboard',
      '--image', 'gcr.io/$PROJECT_ID/switchboard',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--region', 'europe-west4',
    ]

options:
  logging: CLOUD_LOGGING_ONLY
