FROM node:22-slim

WORKDIR /app

# Copy the webapp directory
COPY webapp /app/webapp

# Install dependencies
RUN cd /app/webapp && npm install

# Build the webapp
RUN cd /app/webapp && npm run build

# Expose port
EXPOSE ${PORT}

# Command to start the webapp
CMD ["npm", "run", "start", "--prefix", "/app/webapp"]
